CREATE DATABASE Sinkumunchis;
USE Sinkumunchis;
CREATE TABLE schools ( school_id INT AUTO_INCREMENT PRIMARY KEY,
school_identification VARCHAR(50),
community varchar(255));
CREATE TABLE students(student_id VARCHAR(50) PRIMARY KEY,
    school_identification VARCHAR(50),
    first_name VARCHAR(255),
    last_name VARCHAR(255),
    date_of_birth varchar(50),
    age varchar(50),
    category VARCHAR(255),
    gender_id varchar(255),
    student_level VARCHAR(255),
    shoe_size varchar(50),
    phone_number VARCHAR(20),
    parent_guardian_name VARCHAR(255),
    parent_guardian_phone VARCHAR(20),
    community varchar(255),
    agregado VARCHAR(255),
    shorts_size varchar(50),
    tshit_size varchar(50),
   registration_date varchar(50),
   transport varchar(255),
   evaluation varchar(50),
   DNI_padre varchar(255),
   DNI_Alumno varchar(255),
   Authorization varchar(255));
    CREATE TABLE attendance (attendence_id INT AUTO_INCREMENT PRIMARY KEY,
    student_id VARCHAR(50),
    school_identification VARCHAR(50),
    attendance_count varchar(50),
    Nov_2022_total varchar(50),
    Dec_2022_total varchar(50),
    Feb_2023_total varchar(50),
    March_2023_total varchar(50),
    April_2023_total varchar(50),
    May_2023_total varchar(50),
    June_2023_total varchar(50),
    August_2023_total varchar(50),
    September_2023_total varchar(50),
    October_2023_total varchar(50),
    Nov_2023_total varchar(50),
    Dec_2023_total varchar(50),
    March_2024_total varchar(50),
    FOREIGN KEY(student_id) REFERENCES students(student_id));
    CREATE TABLE Photos (photo_id INT PRIMARY KEY AUTO_INCREMENT,
    student_id VARCHAR(50),
    photo VARCHAR(50),
    photoPG_link VARCHAR(255),
    photoPM_link VARCHAR(255),
    FOREIGN KEY (student_id) REFERENCES students(student_id));